const insuranceOptions = [
  {
    "name": "Life Insurance",
    "provider": "Insurance provider 1",
    "price": 15.99,
    "available": "",
    "index": 0,
  },
  {
    "name": "Home Insurance",
    "provider": "Insurance provider 1",
    "price": 3.99,
    "available": "",
    "index": 1,
  },
  {
    "name": "Crop Insurance",
    "provider": "Insurance provider 1",
    "price": 6.49,
    "available": "N/A",
    "index": 2,
  },
  {
    "name": "Vehicle Insurance",
    "provider": "Insurance provider 1",
    "price": 8.49,
    "available": "N/A",
    "index": 3,
  },
  {
    "name": "Life Insurance",
    "provider": "Insurance provider 2",
    "price": 12.99,
    "available": "",
    "index": 4,
  },
  {
    "name": "Home Insurance",
    "provider": "Insurance provider 2",
    "price": 5.99,
    "available": "N/A",
    "index": 5,
  },
  {
    "name": "Crop Insurance",
    "provider": "Insurance provider 2",
    "price": 14.49,
    "available": "N/A",
    "index": 6,
  },
  {
    "name": "Vehicle Insurance",
    "provider": "Insurance provider 2",
    "price": 3.49,
    "available": "N/A",
    "index": 7,
  },
];
